name: JSer.info
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
jobs:
  jewschool:
    runs-on: ubuntu-latest
    steps:
      - name: Generate cache key
        uses: actions/github-script@v6
        id: generate-key
        with:
          script: |
            core.setOutput('cache-key', new Date().valueOf())

      - name: Retrieve cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/mastofeedbot
          key: feed-cache-${{ steps.generate-key.outputs.cache-key }}
          restore-keys: feed-cache-

      - name: JSer.info
        uses: 'jser/mastofeedbot@main'
        with:
          rss-feed: https://jser.info/rss/
          api-endpoint: https://mstdn.jp
          api-token: ${{ secrets.JSER_MASTODON_TOKEN }}
          cache-file: ${{ github.workspace }}/mastofeedbot/cache.json
